name: Spond Automation

on:
  push:
  schedule:
    # Runs at 16:50 UTC on Wednesdays (10 mins before 17:00 CET)
    - cron: '50 16 * * 3'
    # Runs at 14:50 UTC on Fridays (10 mins before 15:00 CET)
    - cron: '50 14 * * 5'
    # Runs at 14:50 UTC on Sundays (10 mins before 15:00 CET)
    - cron: '50 14 * * 7'

jobs:
  run-bot:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up SafariDriver
        run: |
          sudo safaridriver --enable

      - name: Run the bot script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL1: ${{ secrets.EMAIL1 }}
          PASSWORD1: ${{ secrets.PASSWORD1 }}
        run: |
          python bot.py
