name: Spond Automation

on:
  schedule:
    # Runs at 16:00 UTC on Wednesdays (5 mins before 17:00 CET)
    - cron: '55 16 * * 3'  # Runs 5 minutes before 17:00 CET (Wednesday)
    # Runs at 14:30 UTC on Fridays (to be ready for the 15:00 CET event on Sunday)
    - cron: '30 14 * * 5'  # Runs at 14:30 UTC on Fridays (to be ready for 15:00 CET on Sunday)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up SafariDriver
        run: |
          sudo safaridriver --enable

      - name: Run the bot script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python bot.py
